add documentation for --eval-file flag
denoland/manual pull request #293
Opened 2022-04-19 20:28 UTC by najumancheril

2022-04-19 20:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/manual?pullRequest=293) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/manual?pullRequest=293) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/manual?pullRequest=293) it.</sub>

2022-04-20 00:53 UTC, bartlomieju approved these changes

2022-04-20 00:53 UTC, bartlomieju commented on tools/repl.md
> +$ deno repl --eval-file=https://examples.deno.land/hello-world.ts,https://deno.land/std@0.135.0/encoding/ascii85.ts
Replace hardcoded version of `deno_std` with `@$STD_VERSION` makers, they will be automatically filled with the latest available version

2022-04-20 00:53 UTC, bartlomieju requested changes
Ooops, this was meant to be "Request changes"

2022-04-20 11:39 UTC, najumancheril commented
Do we need the $STD_VERSION?

My system interprets this as an undefined bash environment variable and evaluates it to "". So I see std@.

`$ ./target/debug/deno repl --reload --eval-file=https://examples.deno.land/hello-world.ts,https://deno.land/std@$STD_VERSION/encoding/ascii85.ts
Download https://examples.deno.land/hello-world.ts
Hello, World!
Download https://deno.land/std@/encoding/ascii85.ts
Warning Implicitly using latest version (0.135.0) for https://deno.land/std/encoding/ascii85.ts
Download https://deno.land/std@0.135.0/encoding/ascii85.ts
Deno 1.20.5
exit using ctrl+d or close()
>`

It shows the same thing if I omit the version entirely. Should I do this in the manual example?

`$ ./target/debug/deno repl --reload --eval-file=https://examples.deno.land/hello-world.ts,https://deno.land/std/encoding/ascii85.ts
Download https://examples.deno.land/hello-world.ts
Hello, World!
Download https://deno.land/std/encoding/ascii85.ts
Warning Implicitly using latest version (0.135.0) for https://deno.land/std/encoding/ascii85.ts
Download https://deno.land/std@0.135.0/encoding/ascii85.ts
Deno 1.20.5
exit using ctrl+d or close()
>`

2022-04-20 11:41 UTC, bartlomieju commented
@najumancheril yes, when the site is rendered this marker is replaced with the latest available version of `deno_std` (or a version that matches selected CLI version in manual). So `https://deno.land/std@$STD_VERSION/http/server.ts` gets turned into `https://deno.land/std@0.135.0/http/server.ts` automatically.

2022-04-20 12:21 UTC, bartlomieju approved these changes
LGTM, thank you @najumancheril

2022-04-20 12:21 UTC, merged