add documentation for snapshot testing
denoland/manual pull request #294
Opened 2022-04-19 23:21 UTC by bcheidemann

2022-04-19 23:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/manual?pullRequest=294) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/manual?pullRequest=294) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/manual?pullRequest=294) it.</sub>

2022-04-20 00:56 UTC, bartlomieju requested changes

2022-04-20 00:56 UTC, bartlomieju commented on testing/snapshot_testing.md
> +```ts
```suggestion
```ts, ignore
```
This file is not yet available, because PR hasn't been merged. Let's add this directive for now.

2022-04-20 00:56 UTC, bartlomieju commented on testing/snapshot_testing.md
> +### Basic usage:
```suggestion
### Basic usage
```

2022-04-20 00:56 UTC, bartlomieju commented on testing/snapshot_testing.md
> +### Updating Snapshots:
```suggestion
### Creating and updating snapshots
```

2022-04-20 00:56 UTC, bartlomieju commented on testing/snapshot_testing.md
> +### Permissions:
```suggestion
### Permissions
```

2022-04-20 00:56 UTC, bartlomieju commented on testing/snapshot_testing.md
> +### Version Control:
```suggestion
### Version control
```

2022-04-20 08:15 UTC, bcheidemann commented on testing/snapshot_testing.md
> +```ts
Done :)

2022-04-20 08:15 UTC, bcheidemann commented on testing/snapshot_testing.md
> +### Basic usage:
Done :)

2022-04-20 08:15 UTC, bcheidemann commented on testing/snapshot_testing.md
> +### Updating Snapshots:
Done :)

2022-04-20 08:15 UTC, bcheidemann commented on testing/snapshot_testing.md
> +### Permissions:
Done :)

2022-04-20 08:15 UTC, bcheidemann commented on testing/snapshot_testing.md
> +### Version Control:
Done :)

2022-04-20 08:16 UTC, bcheidemann commented
@bartlomieju all review comments have been addressed now

2022-04-20 11:44 UTC, bartlomieju approved these changes
LGTM

2022-04-20 11:55 UTC, merged