Fix some broken manual links in the introduction
denoland/manual pull request #374
Opened 2022-07-29 15:37 UTC by Announcement

Bring back changes to fix broken manual changes including formatter, tester, linter and compiler.

2022-07-29 15:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/manual?pullRequest=374) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/manual?pullRequest=374) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/manual?pullRequest=374) it.</sub>

2022-08-15 20:52 UTC, jsejcksn requested changes

2022-08-15 20:52 UTC, jsejcksn commented on introduction.md
> +  ([`deno test`](./manual/testing)), and a
```suggestion
  ([`deno fmt`](./tools/formatter)), a linter
  ([`deno lint`](./tools/linter)), a test runner
  ([`deno test`](./testing)), and a
```

This document is already in the `/manual/` path.

2022-08-15 20:52 UTC, jsejcksn commented on introduction.md
> +  [executable](./manual/tools/compiler).
```suggestion
  [executable](./tools/compiler).
```

Same here.

2022-08-20 13:35 UTC, Announcement commented
thank you @Announcement @jsejcksn, sorry for pushing a a second commit instead of accepting i'm not really the best at using git :P

2022-08-26 12:14 UTC, kt3k commented
We landed https://github.com/denoland/dotland/pull/2177, and now `./manual/` redirects to `https://deno.land/manual@$VERSION/introduction` and these links are fixed now.

Thanks for your contribution anyways @Announcement

2022-08-26 12:14 UTC, closed without merging